version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}  # Allows passing DEV or PROD via .env or command line
    volumes:
      - .:/app  # Mounts the current directory into the /app directory inside the container
    command: ./server  # Ensure the binary runs in prod or change for dev mode