version: '3.3'
services:
  app:
    build: .
    environment:
      - ENV=dev
      - ENV=prod
    volumes:
      - ./file-dev.txt:/root/file-dev.txt
      - ./file-prod.txt:/root/file-prod.txt
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3

