FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server server.go

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/server .

COPY file-dev.txt file-prod.txt ./

CMD ["./server"]
